language: ruby
cache: bundler
rvm:
  - 2.2.6
  - 2.3.3
before_script:
  - psql -c 'create database enju_circulation_dummy_test;' -U postgres
  - bundle exec rake db:migrate
after_script:
  - bundle exec codeclimate-test-reporter
services:
  - redis-server
env:
  - DB=postgresql
notifications:
  slack:
    secure: XWkCvx8ImySMHDMgLzqOnEvBSmhUWqXK9TlLBEBG4NDeyXR1SgewcqrBWA7w+wK7fbS2QOJWASV2rkq3eMHMNOgVEjqxmgOMUcDdI7k+GEYuLWsShuIrjtYf9Yezpg4amdbNOYJiu04W3+67FoyCJCYLhDNdheFsYQ5atl+qmfg=
sudo: false
addons:
  postgresql: "9.4"
