language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.3
before_script:
- mysql -e 'create database enju_test'
- psql -c 'create database enju_test;' -U postgres
- bundle exec rake db:migrate
services:
- redis-server
gemfile:
- gemfiles/rails3_2.gemfile
- gemfiles/rails4_1.gemfile
env:
- DB=sqlite
- DB=mysql
- DB=postgresql
matrix:
  exclude:
  - rvm: 1.9.3
    gemfile: gemfiles/rails4_1.gemfile
  - rvm: 2.1.3
    gemfile: gemfiles/rails3_2.gemfile
notifications:
  slack:
    secure: XWkCvx8ImySMHDMgLzqOnEvBSmhUWqXK9TlLBEBG4NDeyXR1SgewcqrBWA7w+wK7fbS2QOJWASV2rkq3eMHMNOgVEjqxmgOMUcDdI7k+GEYuLWsShuIrjtYf9Yezpg4amdbNOYJiu04W3+67FoyCJCYLhDNdheFsYQ5atl+qmfg=
