# http://matthew.mceachen.us/blog/how-to-test-your-rails-application-with-travis-ci-on-different-databases-engines-1220.html
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.3
before_script:
  - mysql -e 'create database enju_test'
  - psql -c 'create database enju_test;' -U postgres
  - "bundle exec rake db:migrate"
services:
  - redis-server
gemfile:
  - gemfiles/rails3_2.gemfile
  - gemfiles/rails4_1.gemfile
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
notifications:
  hipchat:
    rooms:
      secure: bQdet3QlWxCFtswE5K+Cvi3ZnGUn8XdOz174Hkh9yugyKf2gKv7uW5/RANpr957mLP0CSkFXOuWGfE++5eoJNZUR6P70ZO/n45KfkqeVi8v8s7Uc4M32pUVFr9YG6IKaCMfuoAxFtCYr2lkBlKfPONDJzRCnPdXSG/rUFuNntJ0=
