# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63843934c7243e94f35f62f5d31fe044baccbf6d66ad16cdf1ec169aab25c250e6245e851a8849e51a6248a16c6b850cabfa1ff3efcb5e407371916f44e7c9d7

test:
  secret_key_base: 7ad311fef832e8a3e74c49aab509f74a380cf28339ec259aed47d09d9f44e14321f9e13b04754d577ff16fd358e45fb09dc6f56236a47d2b4c5513049242ef76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
