# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6d32357843c8617da5c340256766e6d02aea4134d09f7f93ff5d8da73371767f3b3931477ea119d38f4f729bff5e0377bf8f350c48fe892a8c090b04c38f64a

test:
  secret_key_base: 285a4c7b1f54eff54602b9ca889e25efc521823ce86c03c5f44ac28cd78f2c40a074d3d04c42e10731f00f849460ce22f62a7d850a0c9a381f0c6c7d92c50576

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
